const inforouter = require("./infoRouter");
const wardrouter = require("./wardRouter");
const priestrouter=require("./priestRouter");
const associationrouter=require("./associationRouter");
const contactrouter=require("./contactRouter");
const newsrouter=require("./newsRouter");
const institutionrouter=require("./institutionRouter");
const obituaryrouter=require("./obituaryRouter");
const parishcouncilrouter=require("./parishcouncilRouter");
const userrouter=require("./userRouter");
const express = require("express");
const router = express.Router();

router.use(inforouter);
router.use(wardrouter);
router.use(priestrouter);
router.use(associationrouter);
router.use(newsrouter);
router.use(contactrouter);
router.use(institutionrouter);
router.use(obituaryrouter);
router.use(parishcouncilrouter);
router.use(userrouter);
module.exports = router;
